# Generated by Django 4.0.5 on 2022-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salesforce_Id', models.CharField(max_length=30)),
                ('Date_c', models.DateField()),
                ('Project_Name_c', models.CharField(blank=True, max_length=20, null=True)),
                ('Observation_Location_Latitude_s', models.FloatField()),
                ('Observation_Location_Longitude_s', models.FloatField()),
                ('Trainer_c', models.CharField(blank=True, max_length=20, null=True)),
                ('Number_of_Participants_c', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Session_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salesforce_Id', models.CharField(max_length=30)),
                ('Date_c', models.DateField()),
                ('Project_Name_c', models.CharField(blank=True, max_length=20, null=True)),
                ('Location_GPS_Latitude_s', models.FloatField()),
                ('Location_GPS_Longitude_s', models.FloatField()),
                ('Number_in_Attendance_c', models.IntegerField(blank=True, null=True)),
                ('Module_Name_c', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmvisit',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='training',
            name='module',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='FarmVisit',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='TrainingModule',
        ),
    ]
