# Generated by Django 4.0.5 on 2022-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvisit',
            name='Date_Visited_c',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Farmer_Trainer_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Location_GPS_Latitude_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Location_GPS_Longitude_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Program_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Salesforce_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='Training_Group_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
