# Generated by Django 4.0.5 on 2022-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_observation_c_training_session_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation_c',
            name='Date_c',
            field=models.DateField(blank=True, null=True),
        ),
    ]
