# Generated by Django 4.0.5 on 2022-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_observation_c_date_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session_c',
            name='Date_c',
            field=models.DateField(blank=True, null=True),
        ),
    ]
