# Generated by Django 4.0.5 on 2022-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_training_session_c_date_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session_c',
            name='Trainer_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='training_session_c',
            name='Training_Group_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
