# Generated by Django 4.0.5 on 2022-08-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_demoplot_farmvisit_trainingobservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoplot',
            name='Project_Name_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingobservation',
            name='Project_Name_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='Project_Name_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
