# Generated by Django 4.0.5 on 2022-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_demoplot_project_name_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoplot',
            name='Program_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingobservation',
            name='Program_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='Module_Name_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='Program_c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
